steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/agenticum-containers/backend:latest",
        ".",
      ]
    dir: "backend"

  # 2. Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/agenticum-containers/backend:latest",
      ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "agenticum-backend"
      - "--image"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/agenticum-containers/backend:latest"
      - "--region"
      - "europe-west1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--concurrency"
      - "80"
      - "--timeout"
      - "300"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/agenticum-containers/backend:latest"
