import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { LayoutGrid, PlusCircle, Settings, Type, Image as ImageIcon, FormInput, Sparkles, ChevronRight, Globe, Cpu } from 'lucide-react';

type BlockType = 'text' | 'h1' | 'h2' | 'image' | 'form' | 'agent-prompt';

interface EditorBlock {
  id: string;
  type: BlockType;
  content: string;
  isGenerating?: boolean;
}

interface Page {
  id: string;
  title: string;
  status: 'published' | 'draft';
  blocks: EditorBlock[];
}

const INITIAL_PAGES: Page[] = [
  {
    id: 'p-1',
    title: 'The T-800 Ultimate Guide',
    status: 'published',
    blocks: [
      { id: 'b-1', type: 'h1', content: 'The T-800 Ultimate Guide' },
      { id: 'b-2', type: 'text', content: 'Explore the definitive specifications of the CyberDyne Systems T-800 infiltration unit. Designed absolute perfection in hostile environments.' },
      { id: 'b-3', type: 'image', content: '/assets/ui/hero-blueprint.png' }
    ]
  },
  {
    id: 'p-2',
    title: 'Neon Cortex: Brand Strategy',
    status: 'draft',
    blocks: [
      { id: 'b-4', type: 'h1', content: 'Brand Strategy 2026' }
    ]
  }
];

export function NexusEngineV2() {
  const [pages, setPages] = useState<Page[]>(INITIAL_PAGES);
  const [activePageId, setActivePageId] = useState<string>(INITIAL_PAGES[0].id);
  const activePage = pages.find(p => p.id === activePageId);

  const addBlock = (type: BlockType) => {
    if (!activePage) return;
    const newBlock: EditorBlock = { id: `b-${Date.now()}`, type, content: type === 'text' ? 'Start typing...' : type === 'h2' ? 'New Heading' : '' };
    setPages(prev => prev.map(p => p.id === activePage.id ? { ...p, blocks: [...p.blocks, newBlock] } : p));
  };

  const handlePromptAgent = (blockId: string) => {
    if (!activePage) return;
    // Set to generating
    setPages(prev => prev.map(p => p.id === activePage.id ? {
      ...p,
      blocks: p.blocks.map(b => b.id === blockId ? { ...b, isGenerating: true } : b)
    } : p));

    // Simulate Agent Generation
    setTimeout(() => {
      setPages(prev => prev.map(p => p.id === activePage.id ? {
        ...p,
        blocks: p.blocks.map(b => b.id === blockId ? { 
          ...b, 
          type: 'text', 
          content: 'This paragraph was autonomously generated by CC-06 in response to your directive. The structural integrity of this semantic cluster has been optimized by PM-07 for maximum search visibility.',
          isGenerating: false,
        } : b)
      } : p));
    }, 2500);
  };

  const updateBlockContent = (blockId: string, content: string) => {
    if (!activePage) return;
    setPages(prev => prev.map(p => p.id === activePage.id ? {
      ...p,
      blocks: p.blocks.map(b => b.id === blockId ? { ...b, content } : b)
    } : p));
  };

  return (
    <div className="h-full flex flex-col border border-white/5 rounded-2xl bg-black/20 glass overflow-hidden shadow-[0_50px_100px_rgba(0,0,0,0.5)]">
      
      {/* Header */}
      <div className="p-6 border-b border-white/5 flex items-center justify-between bg-black/40 shrink-0">
        <div>
           <h2 className="text-2xl font-display font-black uppercase italic tracking-tighter text-neural-gold flex items-center gap-2 shadow-neural-gold/50 text-shadow-sm">
             <LayoutGrid size={24} />
             Autonomous Nexus Engine V2
           </h2>
           <p className="text-white/40 font-mono text-xs mt-1">WordPress-Style Block Editor with Inline Swarm Generation</p>
        </div>
        <div className="flex items-center gap-4">
           <button className="flex items-center gap-2 bg-transparent border border-white/10 text-white/50 px-4 py-2 rounded-lg text-[10px] font-black hover:bg-white/5 transition-all uppercase tracking-widest">
             <Settings size={14} /> Global SEO
           </button>
           <button className="flex items-center gap-2 bg-neural-gold text-obsidian px-5 py-2.5 rounded-lg text-xs font-black hover:bg-white transition-all active:scale-95 uppercase tracking-widest shadow-[0_0_15px_rgba(255,215,0,0.3)]">
             <Globe size={16} /> Deploy to Edge
           </button>
        </div>
      </div>

      <div className="flex-1 flex min-h-0">
         
         {/* Left: Page Navigator */}
         <div className="w-1/4 border-r border-white/5 overflow-y-auto scrollbar-none flex flex-col">
            <div className="p-4 border-b border-white/5 flex justify-between items-center bg-black/40 sticky top-0 z-10">
               <span className="text-[10px] font-black uppercase tracking-widest text-white/50">Pillar Pages</span>
               <button className="text-neural-gold hover:text-white transition-colors">
                 <PlusCircle size={16} />
               </button>
            </div>
            <div className="p-3 flex flex-col gap-2">
               {pages.map(page => (
                 <button 
                   key={page.id}
                   onClick={() => setActivePageId(page.id)}
                   className={`w-full text-left p-3 rounded-xl transition-all flex flex-col gap-1 border ${
                     activePageId === page.id 
                       ? 'bg-neural-gold/10 border-neural-gold/30 shadow-[inset_0_0_15px_rgba(255,215,0,0.1)]' 
                       : 'bg-transparent border-transparent hover:bg-white/5'
                   }`}
                 >
                   <span className={`text-sm font-bold truncate ${activePageId === page.id ? 'text-neural-gold' : 'text-white/80'}`}>
                     {page.title}
                   </span>
                   <div className="flex justify-between items-center">
                     <span className={`text-[9px] uppercase font-black tracking-widest ${page.status === 'published' ? 'text-green-500' : 'text-white/30'}`}>
                       {page.status}
                     </span>
                     <ChevronRight size={12} className={activePageId === page.id ? 'text-neural-gold opacity-100' : 'opacity-0'} />
                   </div>
                 </button>
               ))}
            </div>
         </div>

         {/* Center: The WYSIWYG Editor */}
         <div className="flex-1 flex flex-col overflow-y-auto scrollbar-none relative bg-black/20">
            {activePage ? (
              <div className="max-w-3xl w-full mx-auto p-12 flex flex-col gap-6">
                 
                 {/* Page Editor Header */}
                 <div className="mb-4 flex items-center justify-between border-b border-white/10 pb-4">
                    <input 
                      type="text" 
                      value={activePage.title}
                      onChange={(e) => {
                        setPages(prev => prev.map(p => p.id === activePage.id ? { ...p, title: e.target.value } : p));
                      }}
                      className="bg-transparent border-none text-4xl font-black text-white focus:outline-none focus:ring-0 w-full"
                    />
                 </div>

                 {/* Blocks */}
                 <AnimatePresence>
                   {activePage.blocks.map(block => (
                     <motion.div 
                       key={block.id}
                       initial={{ opacity: 0, y: 10 }}
                       animate={{ opacity: 1, y: 0 }}
                       className="group relative"
                     >
                        {block.type === 'h1' && (
                          <input type="text" value={block.content} onChange={e => updateBlockContent(block.id, e.target.value)} className="w-full bg-transparent text-3xl font-bold text-white focus:outline-none placeholder-white/20" placeholder="H1 Heading" />
                        )}
                        {block.type === 'h2' && (
                          <input type="text" value={block.content} onChange={e => updateBlockContent(block.id, e.target.value)} className="w-full bg-transparent text-2xl font-bold text-white/90 focus:outline-none mt-4 placeholder-white/20" placeholder="H2 Heading" />
                        )}
                        {block.type === 'text' && (
                          <textarea 
                            value={block.content} 
                            onChange={e => updateBlockContent(block.id, e.target.value)} 
                            className="w-full bg-transparent text-white/70 font-body text-lg focus:outline-none resize-none min-h-16 placeholder-white/20" 
                            placeholder="Type paragraph..."
                          />
                        )}
                        {block.type === 'image' && (
                          <div className="w-full h-48 border-2 border-dashed border-white/10 rounded-xl flex items-center justify-center bg-white/5 hover:bg-white/10 transition-colors cursor-pointer text-white/30 hover:text-white/60">
                            <div className="flex flex-col items-center gap-2">
                              <ImageIcon size={32} />
                              <span className="text-xs font-mono">Upload Image or Ask DA-03 to Generate</span>
                            </div>
                          </div>
                        )}
                        {block.type === 'form' && (
                          <div className="w-full p-6 border border-neural-gold/20 rounded-xl bg-neural-gold/5 flex flex-col gap-4">
                            <h4 className="text-sm font-bold text-neural-gold flex items-center gap-2"><FormInput size={16} /> Lead Generation Form</h4>
                            <input type="email" disabled placeholder="Email Address" className="w-full bg-black/40 border border-white/10 rounded p-3 text-white/50 cursor-not-allowed" />
                            <button disabled className="w-full bg-neural-gold text-black py-3 rounded font-black text-xs uppercase cursor-not-allowed">Subscribe</button>
                          </div>
                        )}
                        
                        {/* Agent Prompt Block */}
                        {block.type === 'agent-prompt' && (
                          <div className={`w-full p-4 rounded-xl border transition-all ${block.isGenerating ? 'bg-neural-blue/10 border-neural-blue/50 shadow-[0_0_20px_rgba(0,229,255,0.2)]' : 'bg-black/60 border-neural-blue/30 shadow-lg'}`}>
                             {block.isGenerating ? (
                               <div className="flex items-center gap-3">
                                 <Cpu size={20} className="text-neural-blue animate-pulse" />
                                 <div className="flex flex-col">
                                   <span className="text-sm font-black uppercase text-neural-blue tracking-widest">CC-06 Syncing...</span>
                                   <span className="text-[10px] uppercase font-mono text-white/40">Synthesizing neural semantics for the cluster via Gemini 2.0 Thinking.</span>
                                 </div>
                               </div>
                             ) : (
                               <div className="flex flex-col gap-3">
                                 <div className="flex items-center gap-2 text-neural-blue">
                                   <Sparkles size={16} />
                                   <span className="text-[10px] font-black uppercase tracking-widest">Command Swarm Module (Inline)</span>
                                 </div>
                                 <div className="flex gap-2">
                                   <input 
                                     type="text" 
                                     value={block.content}
                                     onChange={e => updateBlockContent(block.id, e.target.value)}
                                     placeholder="e.g. Write a persuasive paragraph explaining the benefits of cybernetic implants..." 
                                     className="flex-1 bg-black/50 border border-white/10 rounded p-3 text-sm font-mono text-white focus:outline-none focus:border-neural-blue/50" 
                                     autoFocus
                                   />
                                   <button 
                                     onClick={() => handlePromptAgent(block.id)}
                                     className="bg-neural-blue text-black px-6 rounded font-black text-[10px] uppercase tracking-widest hover:bg-white transition-colors"
                                   >
                                     Generate
                                   </button>
                                 </div>
                               </div>
                             )}
                          </div>
                        )}

                        {/* Hover Tools / Delete */}
                        <div className="absolute -left-12 top-1/2 transform -translate-y-1/2 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col gap-1">
                          <button 
                            className="w-8 h-8 rounded-full bg-red-500/10 text-red-500 flex items-center justify-center hover:bg-red-500 hover:text-white transition-colors border border-red-500/30"
                            onClick={() => {
                              setPages(prev => prev.map(p => p.id === activePage.id ? { ...p, blocks: p.blocks.filter(b => b.id !== block.id) } : p));
                            }}
                          >
                            ×
                          </button>
                        </div>
                     </motion.div>
                   ))}
                 </AnimatePresence>

                 {/* Block Adder Menu */}
                 <div className="mt-8 pt-8 border-t border-white/10 w-full flex justify-center gap-2">
                   <button onClick={() => addBlock('text')} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 hover:text-white font-mono text-xs transition-colors border border-transparent hover:border-white/10">
                     <Type size={14} /> Text
                   </button>
                   <button onClick={() => addBlock('h2')} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 hover:text-white font-mono text-xs transition-colors border border-transparent hover:border-white/10">
                     H2
                   </button>
                   <button onClick={() => addBlock('image')} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 hover:text-white font-mono text-xs transition-colors border border-transparent hover:border-white/10">
                     <ImageIcon size={14} /> Image
                   </button>
                   <button onClick={() => addBlock('form')} className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-white/50 hover:text-white font-mono text-xs transition-colors border border-transparent hover:border-white/10">
                     <FormInput size={14} /> Form
                   </button>
                   <button onClick={() => addBlock('agent-prompt')} className="flex items-center gap-2 px-4 py-2 bg-neural-blue/10 hover:bg-neural-blue/20 rounded-lg text-neural-blue font-black tracking-widest uppercase text-[10px] transition-colors border border-neural-blue/30 hover:shadow-[0_0_15px_rgba(0,229,255,0.3)]">
                     <Sparkles size={14} /> Agent Prompt
                   </button>
                 </div>

              </div>
            ) : (
              <div className="flex-1 flex items-center justify-center text-white/20">
                <p className="font-mono text-sm">Select a page to edit.</p>
              </div>
            )}
         </div>

      </div>
    </div>
  );
}
